const { createClient } = window.supabase;
const supabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id);
const dashboardUrl=()=>new URL('student-dashboard.html',window.location.href).href;
const loginUrl=()=>new URL('student-login.html',window.location.href).href;
function message(text,ok=false){const el=$('authMessage');if(!el)return;el.textContent=text;el.className='auth-message '+(ok?'success':'');}
function busy(btn,on,label){if(!btn)return;btn.disabled=on;if(on){btn.dataset.old=btn.textContent;btn.textContent=label}else btn.textContent=btn.dataset.old||btn.textContent}
async function ensureProfile(user){const {data,error}=await supabaseClient.from('students').select('*').eq('id',user.id).maybeSingle();if(error)throw error;if(data)return data;const m=user.user_metadata||{};const profile={id:user.id,full_name:m.full_name||user.email?.split('@')[0]||'Student',email:user.email||'',phone:m.phone||'',country:m.country||'',programme:m.programme||''};const res=await supabaseClient.from('students').insert(profile).select().single();if(res.error)throw res.error;return res.data}
$('loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=$('loginBtn');const fd=new FormData(e.currentTarget);const email=String(fd.get('email')||'').trim();const password=String(fd.get('password')||'');message('Signing you in…',true);busy(btn,true,'Checking account…');try{const {data,error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw new Error('Login succeeded but a secure session was not returned. Please try again.');window.location.replace(dashboardUrl())}catch(err){console.error(err);message(err.message||'Unable to log in. Please check your email and password.')}finally{busy(btn,false)}});
$('registerForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=$('registerBtn');const fd=new FormData(e.currentTarget);const email=String(fd.get('email')||'').trim();const password=String(fd.get('password')||'');if(password.length<6){message('Please use a password of at least 6 characters.');return}message('Creating your student account…',true);busy(btn,true,'Creating account…');try{const {data,error}=await supabaseClient.auth.signUp({email,password,options:{data:{full_name:String(fd.get('full_name')||''),phone:String(fd.get('phone')||''),country:String(fd.get('country')||''),programme:String(fd.get('programme')||'')},emailRedirectTo:dashboardUrl()}});if(error)throw error;e.currentTarget.reset();if(data.session){window.location.replace(dashboardUrl())}else{message('Account created. If email confirmation is enabled, confirm your email first, then return to Student Login.',true)}}catch(err){console.error(err);message(err.message||'Unable to create the account.')}finally{busy(btn,false)}});
async function loadClasses(){const list=$('classesList');if(!list)return;list.innerHTML='<p class="muted">Loading classes…</p>';const {data,error}=await supabaseClient.from('classes').select('id,title,programme,start_time,duration_minutes,zoom_link,tutor').order('start_time',{ascending:true});if(error){console.error(error);list.innerHTML='<div class="empty-card"><strong>Classes could not be loaded.</strong><p>Please check your connection or ask the academy to review the class schedule.</p></div>';return}if(!data?.length){list.innerHTML='<div class="empty-card"><strong>No classes scheduled yet.</strong><p>Your tutor will add the next class to your dashboard.</p></div>';return}list.innerHTML=data.map(c=>{const d=new Date(c.start_time);const date=d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'});const link=c.zoom_link||'';return `<article class="class-card"><div><span class="eyebrow">${esc(c.programme||'CLASS')}</span><h4>${esc(c.title)}</h4><p>${esc(date)}${c.duration_minutes?` · ${esc(c.duration_minutes)} minutes`:''}</p>${c.tutor?`<p>Tutor: ${esc(c.tutor)}</p>`:''}</div><a class="btn primary" href="${esc(link||'#')}" target="_blank" rel="noopener" ${link?'':'aria-disabled="true"'}>${link?'Join Zoom Class':'Zoom link pending'}</a></article>`}).join('')}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function dashboard(){if(!$('dashboard'))return;const {data:{session}}=await supabaseClient.auth.getSession();if(!session){window.location.replace(loginUrl());return}try{const p=await ensureProfile(session.user);$('studentName').textContent=p.full_name||'Student';$('studentEmail').textContent=p.email||session.user.email||'';$('studentProgramme').textContent=p.programme||'Programme to be confirmed';$('dashboard').hidden=false;await loadClasses();const n=$('topNotification');if(n)n.hidden=false;$('notificationText').textContent=`Assalamu Alaikum, ${p.full_name||'Student'}! Your student dashboard is ready.`}catch(err){console.error(err);$('dashboardError').hidden=false}}
$('closeNotification')?.addEventListener('click',()=>{$('topNotification').hidden=true});$('logoutBtn')?.addEventListener('click',async()=>{await supabaseClient.auth.signOut();window.location.replace(new URL('index.html',window.location.href).href)});dashboard();
